version-history/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :versions, only: %i[index show update]
  end

  root 'application#home'
end

version-history/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

version-history/app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  has_paper_trail

  belongs_to :user
  belongs_to :channel

  validates :body, presence: true

  default_scope { order(created_at: :asc) }
end

version-history/app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_paper_trail

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

version-history/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_many :posts
end

version-history/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_paper_trail_whodunnit

  def home
    redirect_to posts_path
  end

  private

  def not_found
    raise ActionController::RoutingError, 'Not Found'
  end
end

version-history/app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all.order(published_at: :desc)
  end

  def new
    @post = Post.new
  end

  def show; end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was created successfully.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was deleted successfully.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user, :published_at)
  end

  def set_post
    @post = Post.find(params[:id])
    not_found unless @post
  end
end

version-history/app/controllers/versions_controller.rb
# frozen_string_literal: true

class VersionsController < ApplicationController
  before_action :set_post
  before_action :set_versions, only: %i[index show]
  before_action :set_version, only: %i[show update]
  before_action :authenticate_user!

  def index
    redirect_to post_version_path(@post, @versions.first.id) if @versions.first
  end

  def show; end

  def update; end

  private

  def set_post
    @post = Post.find(params[:post_id])
    not_found unless @post
  end

  def set_versions
    @versions = @post.versions.includes(:user)
    not_found if @versions.empty?
  end

  def set_version
    @version = @post.versions.find(params[:id])
    not_found unless @version
  rescue StandardError
    not_found
  end
end

version-history/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def secondary_button_classes
    %w[
      bg-stone-200
      duration-300
      hover:bg-pink-500
      hover:text-white
      leading-none
      no-underline
      p-2
      rounded-md
      text-inherit
      transition-colors
    ].join(' ')
  end

  def markdown(text)
    options = %i[hard_wrap autolink no_intra_emphasis fenced_code_blocks]
    Markdown.new(text, *options).to_html.html_safe
  end
end

version-history/app/helpers/versions_helper.rb
# frozen_string_literal: true

module VersionsHelper
  def version_link_class(version)
    classes = %w[
      block
      border-b
      border-l-[.35rem]
      no-underline
      p-4
      text-inherit
    ]
    if version.id == @version.id
      classes.push('border-l-pink-500')
    else
      classes.push('border-l-stone-100', 'hover:border-l-stone-300')
    end
    classes.join(' ')
  end
end

version-history/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ultimate PaperTrail Guide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("favicon.png") %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body class="bg-stone-50">
    <%# Alerts %>
    <% if notice || alert %>
      <div class="fixed left-0 z-50 w-full text-center text-white top-2" data-fade-out>
        <% if notice %>
          <p class="inline-block px-3 py-2 mb-0 bg-blue-500 rounded-md"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="inline-block px-3 py-2 mb-0 bg-red-500 rounded-md"><%= alert %></p>
        <% end %>
      </div>
    <% end %>
    <%# Header %>
    <div class="sticky top-0 z-50">
      <div class="flex items-center justify-between w-full px-4 py-3 mx-auto bg-white border-b border-gray-200">
        <a href="/" class="flex items-center justify-center w-10 h-10 no-underline bg-pink-500 rounded-full">
          <span class="block font-bold leading-none text-white">PT</span>
        </a>
        <div class="flex items-center space-x-2">
          <% if user_signed_in? %>
            <div class="flex-shrink-0">
              <%= image_tag "https://i.pravatar.cc/400?img=#{current_user.id}", class: "rounded-full h-8 w-8 border border-stone-300" %>
            </div>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-sm no-underline hover:underline' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'text-sm no-underline hover:underline' %>
          <% end %>
        </div>
      </div>
    </div>
    <%# Main Content %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>
<script>
  $(document).ready(function() {
    setTimeout(function() {
      $('[data-fade-out]').fadeOut(1000);
    }, 2500);
  });
</script>

version-history/app/views/messages/index.html.erb
<div class="flex h-screen">
  <%# --- Channels (Left Col) --- %>
  <div class="text-white bg-stone-800">
    <div class="px-8 py-6 border-b border-stone-600">
      <h2 class="mb-1 text-sm font-extralight">Ultimate PaperTrail Guide</h2>
      <h1 class="mb-0 text-2xl font-bold">Edited State Example</h1>
    </div>
    <div class="py-4">
      <h2 class="mx-6 mb-4 text-sm font-extralight">Channels</h2>
      <nav>
        <% Channel.all.each do |channel| %>
          <%= link_to "##{channel.title}", channel_messages_path(channel), class: channel_link_classes(channel) %>
        <% end %>
      </nav>
    </div>
  </div>
  <%# --- Messages (Right Col) --- %>
  <div class="relative flex-grow">
    <%# --- Header --- %>
    <div class="absolute top-0 left-0 right-0 z-10">
      <div class="flex items-center justify-between w-full px-4 py-3 mx-auto bg-white border-b border-gray-200">
        <div>
          <span class="font-bold">#<%= @channel.title %></span>
        </div>
        <div class="flex items-center space-x-2">
          <% if user_signed_in? %>
            <div class="flex-shrink-0">
              <%= image_tag "https://i.pravatar.cc/400?img=#{current_user.id}", class: "rounded-full h-8 w-8 border border-stone-300" %>
            </div>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-sm no-underline hover:underline' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'text-sm no-underline hover:underline' %>
          <% end %>
        </div>
      </div>
    </div>
    <%# --- Messages --- %>
    <div class="relative z-0 h-full pt-16 pb-20 overflow-y-scroll">
      <% @messages.group_by { |x| message_group(x) }.each do |date, messages| %>
        <div class="relative my-4 text-center">
          <div class="w-full h-[1px] bg-stone-200 absolute top-[12px]"></div>
          <span class="relative inline-block px-3 py-1 mx-auto text-xs border rounded-full bg-gray-50 border-stone-400"><%= date %></span>
        </div>
        <% messages.each do |message| %>
          <div class="flex px-4 mb-6 space-x-2" id="message-<%= message.id %>">
            <div class="mt-1">
              <%= image_tag "https://i.pravatar.cc/400?img=#{message.user.id}", class: "rounded-lg h-10 w-10" %>
            </div>
            <div class="relative flex-grow">
              <div class="flex items-center mb-1 space-x-2 text-sm">
                <span class="font-bold "><%= message.user.name %></span>
                <span class="text-stone-500"><%= message.created_at.to_fs(:time) %></span>
                <% if message.versions.select { |v| v.event == 'update' }.size > 0 %>
                  <span class="px-1 py-[2px] text-xs text-blue-400 uppercase bg-blue-100 border border-blue-200 rounded-sm">Edited</span>
                <% end %>
              </div>
              <div class="flex-grow">
                <%= message.body %>
              </div>
              <% if message.user == current_user %>
                <div class="absolute top-2 right-4">
                  <%= link_to 'Edit', edit_channel_message_path(@channel, message), class: 'text-xs p-2 border border-stone-300 text-stone-500 uppercase no-underline rounded-md hover:text-pink-500 hover:border-pink-500 duration-300 transition-colors' %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%# --- New Message Form --- %>
    <div class="absolute bottom-0 left-0 right-0 z-10 bg-white border-t border-stone-300">
      <%= simple_form_for [@channel, @message], html: { class: 'relative'} do |f| %>
        <%= f.input :body, label: false, placeholder: 'New message ...' %>
        <%= f.submit 'Send', class: 'bg-blue-500 absolute right-4 top-3 text-sm text-white rounded-md py-2 px-4' %>
      <% end %>
    </div>
  </div>
</div>
<%# Scroll to latest message %>
<script type="text/javascript">
  var lastMessage = document.getElementById("message-<%= @messages.last.id %>");
  lastMessage.scrollIntoView();
</script>

version-history/app/views/posts/_actions.html.erb
<%= link_to edit_post_path(post), class: secondary_button_classes + ' mr-3' do %>
  <span class="inline-block h-3"><%= render 'shared/icons/edit' %></span>
<% end %>
<%= link_to post_versions_path(post), class: secondary_button_classes + ' mr-3' do %>
  <span class="inline-block h-3"><%= render 'shared/icons/history' %></span>
<% end %>
<%= link_to post, data: {confirm: 'Are you sure?'}, method: :delete, class: secondary_button_classes do %>
  <span class="inline-block h-3"><%= render 'shared/icons/delete' %></span>
<% end %>

version-history/app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :body, input_html: { rows: 10 } %>
  <%= f.input :user_id, collection: User.all %>
  <%= f.input :image_url %>
  <%= f.input :published_at, as: :date, html5: true %>
  <div class="flex items-center space-x-3">
    <%= f.submit 'Save Post', class: 'button' %>
    <%= link_to 'Cancel', @post %>
  </div>
<% end %>

version-history/app/views/posts/_post.html.erb
<div>
  <%= link_to post, class: "relative mb-3 pb-[56.25%] block" do %>
    <%= image_tag post.image_url, class: 'absolute object-center object-fill h-full w-full' %>
  <% end %>
  <h2 class="mb-1 text-xl font-semibold"><%= link_to post.title, post, class: 'text-inherit no-underline' %></h2>
  <div class="flex items-center justify-between text-sm text-stone-500">
    <span><%= post.published_at.strftime('%b %d, %Y') %></span>
    <div class="flex items-center">
      <%= render partial: 'actions', locals: { post: post } %>
    </div>
  </div>
</div>

version-history/app/views/posts/edit.html.erb
<div class="max-w-3xl px-8 py-16 mx-auto">
  <h1 class="text-4xl">Edit Post #<%= @post.id %></h1>
  <%= render 'form' %>
</div>

version-history/app/views/posts/index--bak.html.erb
<div class="flex h-screen">
  <%# --- Channels (Left Col) --- %>
  <div class="text-white bg-stone-800">
    <div class="px-8 py-6 border-b border-stone-600">
      <h2 class="mb-1 text-sm font-extralight">Ultimate PaperTrail Guide</h2>
      <h1 class="mb-0 text-2xl font-bold">Edited State Example</h1>
    </div>
    <div class="py-4">
      <h2 class="mx-6 mb-4 text-sm font-extralight">Channels</h2>
      <nav>
        <% Channel.all.each do |channel| %>
          <%= link_to "##{channel.title}", channel_posts_path(channel), class: channel_link_classes(channel) %>
        <% end %>
      </nav>
    </div>
  </div>
  <%# --- Posts (Right Col) --- %>
  <div class="relative flex-grow">
    <%# --- Header --- %>
    <div class="absolute top-0 left-0 right-0 z-10">
      <div class="flex items-center justify-between w-full px-4 py-3 mx-auto bg-white border-b border-gray-200">
        <div>
          <span class="font-bold">#<%= @channel.title %></span>
        </div>
        <div class="flex items-center space-x-2">
          <% if user_signed_in? %>
            <div class="flex-shrink-0">
              <%= image_tag "https://i.pravatar.cc/400?img=#{current_user.id}", class: "rounded-full h-8 w-8 border border-stone-300" %>
            </div>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-sm no-underline hover:underline' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'text-sm no-underline hover:underline' %>
          <% end %>
        </div>
      </div>
    </div>
    <%# --- Posts --- %>
    <div class="relative z-0 h-full pt-16 pb-20 overflow-y-scroll">
      <% @posts.group_by { |x| post_group(x) }.each do |date, posts| %>
        <div class="relative my-4 text-center">
          <div class="w-full h-[1px] bg-stone-200 absolute top-[12px]"></div>
          <span class="relative inline-block px-3 py-1 mx-auto text-xs border rounded-full bg-gray-50 border-stone-400"><%= date %></span>
        </div>
        <% posts.each do |post| %>
          <div class="flex px-4 mb-6 space-x-2" id="post-<%= post.id %>">
            <div class="mt-1">
              <%= image_tag "https://i.pravatar.cc/400?img=#{post.user.id}", class: "rounded-lg h-10 w-10" %>
            </div>
            <div class="relative flex-grow">
              <div class="flex items-center mb-1 space-x-2 text-sm">
                <span class="font-bold "><%= post.user.name %></span>
                <span class="text-stone-500"><%= post.created_at.to_fs(:time) %></span>
                <% if post.versions.select { |v| v.event == 'update' }.size > 0 %>
                  <span class="px-1 py-[2px] text-xs text-blue-400 uppercase bg-blue-100 border border-blue-200 rounded-sm">Edited</span>
                <% end %>
              </div>
              <div class="flex-grow">
                <%= post.body %>
              </div>
              <% if post.user == current_user %>
                <div class="absolute top-2 right-4">
                  <%= link_to 'Edit', edit_channel_post_path(@channel, post), class: 'text-xs p-2 border border-stone-300 text-stone-500 uppercase no-underline rounded-md hover:text-pink-500 hover:border-pink-500 duration-300 transition-colors' %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%# --- New Post Form --- %>
    <div class="absolute bottom-0 left-0 right-0 z-10 bg-white border-t border-stone-300">
      <%= simple_form_for [@channel, @post], html: { class: 'relative'} do |f| %>
        <%= f.input :body, label: false, placeholder: 'New post ...' %>
        <%= f.submit 'Send', class: 'bg-blue-500 absolute right-4 top-3 text-sm text-white rounded-md py-2 px-4' %>
      <% end %>
    </div>
  </div>
</div>
<%# Scroll to latest post %>
<script type="text/javascript">
  var lastPost = document.getElementById("post-<%= @posts.last.id %>");
  lastPost.scrollIntoView();
</script>

version-history/app/views/posts/index.html.erb
<div class="max-w-6xl px-8 py-16 mx-auto">
  <h1 class="mb-12 font-semibold text-7xl">The Blog</h1>
  <div class="grid gap-6 lg:gap-8 sm:grid-cols-2 lg:grid-cols-3">
    <%= render @posts %>
  </div>
</div>

version-history/app/views/posts/show.html.erb
<div class="max-w-4xl px-8 py-16 mx-auto">
  <div class="relative mb-4 pb-[40%] block">
    <%= image_tag @post.image_url, class: 'absolute object-center object-fill h-full w-full' %>
  </div>
  <%# Meta %>
  <div class="flex items-center justify-between mb-2 text-sm text-stone-500">
    <span><%= @post.published_at.strftime('%b %d, %Y') %></span>
    <div class="flex items-center">
      <%= render partial: 'actions', locals: { post: @post } %>
    </div>
  </div>
  <%# Title %>
  <h1 class="mb-8 text-5xl font-semibold"><%= @post.title %></h1>
  <%# Body %>
  <div><%= markdown @post.body %></div>
</div>

version-history/app/views/shared/icons/_delete.html.erb
<svg width="200" height="200" viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M86.4706 0C70.251 0 57.0588 13.1922 57.0588 29.4118V35.2941H25.6863C17.0235 35.2941 10 42.3176 10 50.9804C10 59.6431 17.0235 66.6667 25.6863 66.6667H26.5977L32.2426 168.298C33.2309 186.075 47.9559 200 65.7598 200H134.632C152.436 200 167.161 186.075 168.15 168.298L173.794 66.6667H174.706C183.369 66.6667 190.392 59.6431 190.392 50.9804C190.392 42.3176 183.369 35.2941 174.706 35.2941H143.333V29.4118C143.333 13.1922 130.141 0 113.922 0H86.4706ZM86.4706 27.451H113.922C115 27.451 115.882 28.3294 115.882 29.4118V35.2941H84.5098V29.4118C84.5098 28.3294 85.3922 27.451 86.4706 27.451ZM54.087 66.6667H146.305L140.744 166.766C140.56 170.009 137.875 172.549 134.632 172.549H65.7598C62.5167 172.549 59.832 170.013 59.6477 166.774L54.087 66.6667ZM100.196 74.5098C95.8667 74.5098 92.3529 78.0235 92.3529 82.3529V152.642C92.3529 156.972 95.8667 160.486 100.196 160.486C104.525 160.486 108.039 156.972 108.039 152.642V82.3529C108.039 78.0235 104.525 74.5098 100.196 74.5098ZM74.2846 74.5175C69.9552 74.6665 66.5682 78.2916 66.7172 82.621L69.1682 153.209C69.3172 157.445 72.7958 160.784 77.0037 160.784C77.0939 160.784 77.1816 160.781 77.2718 160.777C81.6012 160.628 84.9958 157.003 84.8468 152.673L82.3958 82.0849C82.2429 77.7555 78.4689 74.4312 74.2846 74.5175ZM126.108 74.5175C121.841 74.4312 118.145 77.7555 117.996 82.0849L115.545 152.673C115.396 157.003 118.791 160.624 123.12 160.777C123.211 160.781 123.298 160.784 123.388 160.784C127.592 160.784 131.075 157.445 131.224 153.209L133.675 82.621C133.824 78.2916 130.437 74.6704 126.108 74.5175Z" fill="currentColor" />
</svg>

version-history/app/views/shared/icons/_edit.html.erb
<svg width="200" height="200" viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M162.251 0C159.556 0 156.861 1.03123 154.809 3.08384L133.756 24.1362L118.872 39.0208L0 157.892V199.997H42.1046L196.913 45.1885C201.029 41.0727 201.029 34.409 196.913 30.3038L169.693 3.08384C167.641 1.03123 164.946 0 162.251 0ZM162.251 25.4108L174.586 37.7462L160.976 51.3561L148.641 39.0208L162.251 25.4108ZM133.756 53.9055L146.092 66.2408L33.3877 178.945H21.0523V166.609L133.756 53.9055Z" fill="currentColor" />
</svg>

version-history/app/views/shared/icons/_history.html.erb
<svg width="200" height="200" viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M99.7426 0C156.87 0 202.854 49.0879 198.497 107.682C194.861 156.573 155.767 196.043 107.345 199.712C52.0851 203.898 5.36549 161.995 1.03046 108.18C0.937123 107.147 1.05883 106.106 1.38791 105.123C1.71699 104.139 2.2463 103.235 2.94244 102.466C3.63859 101.698 4.48646 101.082 5.43257 100.657C6.37868 100.233 7.40249 100.009 8.43942 100C10.4365 99.9957 12.3629 100.739 13.8391 102.084C15.3153 103.429 16.2345 105.278 16.4155 107.267C18.2132 129.252 28.587 149.648 45.2961 164.049C62.0053 178.45 83.7087 185.7 105.718 184.233C127.39 182.479 147.55 172.437 162.006 156.197C176.461 139.956 184.099 118.768 183.329 97.039C182.559 75.3105 173.442 54.7154 157.873 39.5385C142.304 24.3616 121.484 15.7716 99.7426 15.5556C88.7427 15.5782 77.856 17.7768 67.7095 22.0248C57.563 26.2727 48.3571 32.486 40.622 40.3069L57.5982 57.4477C57.8058 57.6565 57.9473 57.922 58.0048 58.2108C58.0623 58.4997 58.0334 58.799 57.9216 59.0715C57.8098 59.344 57.6202 59.5775 57.3764 59.7427C57.1326 59.9079 56.8455 59.9975 56.551 60.0004H8.78613C8.39143 59.9985 8.01365 59.8399 7.73588 59.5595C7.45812 59.279 7.30312 58.8998 7.30498 58.5051V10.2772C7.30213 9.9831 7.38704 9.69478 7.54886 9.44913C7.71068 9.20348 7.94207 9.01165 8.21345 8.89815C8.48483 8.78465 8.78389 8.75463 9.07241 8.81193C9.36094 8.86924 9.62583 9.01125 9.83324 9.21984L29.7305 29.3099C38.8903 20.0479 49.7921 12.6899 61.808 7.65953C73.8239 2.6292 86.7163 0.0260402 99.7426 0V0ZM99.7426 38.6882C97.6897 38.6981 95.7249 39.5231 94.2803 40.9817C92.8356 42.4403 92.0296 44.4131 92.0395 46.4659V100C92.0296 102.053 92.8357 104.026 94.2803 105.484C95.7249 106.943 97.6897 107.768 99.7426 107.778H152.764C154.814 107.758 156.773 106.93 158.216 105.474C159.658 104.017 160.468 102.05 160.468 100C160.468 97.95 159.658 95.9829 158.216 94.5264C156.773 93.0699 154.814 92.2418 152.764 92.2222H107.446V46.4659C107.456 44.4131 106.65 42.4403 105.205 40.9817C103.76 39.5231 101.795 38.6981 99.7426 38.6882V38.6882Z" fill="currentColor" />
</svg>

version-history/app/views/versions/_version.html.erb
<%= link_to post_version_path(@post, version.id), class: version_link_class(version) do %>
  <div class="flex items-center mb-2 space-x-3 text-sm">
    <span class="block font-semibold">
      <%= version.created_at.strftime('%b %d, %Y') %>
    </span>
    <span class="text-stone-300">|</span>
    <div class="flex items-center space-x-1">
      <%= image_tag "https://i.pravatar.cc/400?img=#{version.user.id}", class: "rounded-full h-8 w-8 border border-stone-300" %>
      <span class=""><%= version.user.name %></span>
    </div>
  </div>
  <div class="flex items-center space-x-2">
    <span class="inline-block p-1 text-xs uppercase border rounded-md border-stone-300 bg-stone-200 text-stone-500"><%= version.event %></span>
    <% if version.event == 'update' %>
      <span class="font-mono text-sm"><%= version.changeset.keys.excluding('updated_at').join(', ') %></span>
    <% end %>
  </div>
<% end %>

version-history/app/views/versions/show.html.erb
<div class="flex">
  <div class="min-h-screen border-r border-stone-200">
    <%= render partial: 'versions/version', collection: @versions %>
  </div>
  <div>
    Render post
  </div>
</div>